### ISSUE TITLE
Sectopod and Berserker stats disappear after certain research levels

### ISSUE THREAD

**Issue by elmacsee** [chrishayesmu/XCOM-Companion#14]
Bit of a weird one.
When viewing the details of the Berserker and Sectopod if you manually enter difficulty level and alien research rate, the stats window on the left disappears once you reach a certain research level.

The levels that it cuts off from seems to match research upgrades so maybe some value from them isn't being applied correctly.
I've been unable to reproduce the issue on other aliens, seems to just be the Sectopod and Berserker.

_Berserker_
Impossible - 924 research
![923](https://user-images.githubusercontent.com/88979660/138730095-b739657a-78a8-4cce-aadf-c9e60267c714.JPG)
![924](https://user-images.githubusercontent.com/88979660/138730115-e5b56a9f-3e5d-471c-b4df-1e24c6a07b0d.JPG)

_Sectopod_
Classic - 900 research
Brutal - 819 research
Impossible - 693 researh

**Comment by chrishayesmu** [comment]
Ah, damn, someone finally hit this in the wild. I found this out a while back - it happens when the damage stat reaches 21 or higher. I already fixed it but I've been super lazy about putting out a release the last few weeks. I just published version 0.7.9, which fixes this and a few other things. Sorry I didn't release it sooner to save you the time of this report, but I appreciate you putting it together.
