### ISSUE TITLE
Idea: show viable map selections

### ISSUE THREAD

**Issue by tkoeppe** [chrishayesmu/XCOM-Companion#6]
Here's an idea for making the Maps constraint selection communicate more information quickly:

* If nothing is selected, the AO and Type menus are fully enabled.
* If only an AO xor a Type is selected, the respective other menu's entries that would result in no matching maps are "disabled" (they could still be selected, but appear, say, gray).
* If an AO and a UFO mission type are selected, only viable UFO types are enabled.
* If a UFO mission type and a UFO type are selected, only viable AOs are enabled.

I could take a stab at this if you like it. I don't know much about JS, but it seems learnable. If you happen to know how to implement this in five minutes, though, I'd also be more than happy to just leave it to you :-)

**Comment by chrishayesmu** [comment]
Oh, this is a great idea! Should be pretty quick, too. I'll see if I can't knock it out tonight.

**Comment by chrishayesmu** [comment]
Just pushed a version of this in https://github.com/chrishayesmu/XCOM-Companion/commit/0ed999f9bb41fe131ae05e82e977e2d1e68cf903. It's a similar idea, but the AO list is never disabled, because otherwise you might have to click around a bunch of times before reaching a configuration that lets you click the AO you actually want. Instead, if you select a new AO and it invalidates your other selections, they're just unset.

Thanks for the suggestion!

**Comment by tkoeppe** [comment]
Aha, OK! I had thought that we shouldn't outright _ban_ people from trying to make an invalid selection, just highlight which choices would succeed.

Could you check: at the moment, if you unselect the AO, the Type menu doesn't seem to reset. I.e. you also need some logic to reset things when nothing is selected.

**Comment by chrishayesmu** [comment]
Ah, whoops. Fixed that in https://github.com/chrishayesmu/XCOM-Companion/commit/5c51ad4136e0d0d0f1ec2809fa48d2168fa98943. Nice catch.

A neat side effect is that if you select "UFO: Landed" with no AO, you can see which UFO types never have landings.
